@base_url= http://localhost:5223

# CLIENTE ######################################
###criar cliente
POST {{base_url}}/clientes/cadastrar
Content-Type: application/json

[
    {
        "nome": "Thiago Schwantes",
        "cpf" : "12345678910",
        "rg" : "123456789",
        "cep" : "81220450",
        "endereco" : "rua mario souza francisco 220",
        "bairro" : "boqueirão",
        "cidade" : "curitiba",
        "telefone" : "41999889988"
    },
    
    {
        "nome": "Vinicius Ferreira Geraldo",
        "cpf" : "0957261901",
        "rg" : "109103500",
        "cep" : "81333900",
        "endereco" : "rua caronel tadalafila 850",
        "bairro" : "campo cumprido",
        "cidade" : "paranagua",
        "telefone" : "41986861122"
    }
]

### listar cliente
GET {{base_url}}/clientes/listar

### alterar cliente
PUT {{base_url}}/clientes/alterar/12345678910
Content-Type: application/json

{
    "nome": "Marcos Lopes",
    "cpf" : "83374465510",
    "rg" : "999999999",
    "cep" : "82666300",
    "endereco" : "rua jose alfredo lopes 850",
    "bairro" : "fazendinha",
    "cidade" : "Londrina",
    "telefone" : "41984562020"
}

### deletar cliente
DELETE {{base_url}}/clientes/deletar/12345678910

# PRODUTO ######################################
###criar produto
POST {{base_url}}/produto/cadastrar
Content-Type: application/json

[
    {
        "nome": "lona",
        "descricao" : "lona 440g branco front-light com fundo black",
        "preco" : 35.00
    },
    
    {
        "nome": "adesivo",
        "descricao" : "adesivo 12mm black-out",
        "preco" : 30.00
    }
]

### listar produto
GET {{base_url}}/produto/listar

### alterar produto
PUT {{base_url}}/produto/alterar/a8dbd926-bb9f-4946-a73f-3465f2496da3
Content-Type: application/json

{
    "nome": "adesivo transparente",
    "descricao" : "adesivo transparente 10mm brilho,marca viniLona",
    "preco" : 45.00
    
}

### deletar produto
DELETE {{base_url}}/produto/deletar/a8dbd926-bb9f-4946-a73f-3465f2496da3

# ACABAMENTO ######################################
###criar acabamento
POST {{base_url}}/acabamentos/cadastrar
Content-Type: application/json

[
    {
        "nome": "acabamento de adesivo",
        "descricao" : "refile com estilete pequeno na linha de corte e aplicação se necessario"
    },
    
    {
        "nome": "acabamento de banner",
        "descricao" : "refile com estilete grande,solda com maquina de solda,grampeia as madeiras e bambante encima e embaixo,depois coloca a ponteira e grampeia."
    }
]

### listar acabamento
GET {{base_url}}/acabamentos/listar

### alterar acabamento
PUT {{base_url}}/acabamentos/alterar/ce75079c-b84f-4a64-80c8-6101a0b5afa2
Content-Type: application/json

{
    "nome": "acabamento em lona",
    "descricao" : "solda com a maquina de solda e depois passa ela pela maquina de ilhós."
}

### deletar acabamento
DELETE {{base_url}}/acabamentos/deletar/ce75079c-b84f-4a64-80c8-6101a0b5afa2

# EQUIPAMENTO ######################################
###criar equipamento
POST {{base_url}}/equipamentos/cadastrar
Content-Type: application/json

[
    {
        "nome": "My Jet",
        "descricao" : "Maquina de impressão para grandes formatos,com capacidade de ate 3.20 de largura, 8 cabeças com tinta a base de solvente."
    },
    
    {
        "nome": "Rolland",
        "descricao" : "Maquina de impressão para impressão de adesivo com 4 cabeças e tinta a base de solvente."
    }
]

### listar equipamento
GET {{base_url}}/equipamentos/listar

### alterar equipamento
PUT {{base_url}}/equipamentos/alterar/dfabb9d2-ce78-4a1f-834b-b1aa51df04aa
Content-Type: application/json

{
    "nome": "Plotter",
    "descricao" : "Maquina para corte de adesivo e corte contorno após impressão."
}

### deletar equipamento
DELETE {{base_url}}/equipamentos/deletar/dfabb9d2-ce78-4a1f-834b-b1aa51df04aa

# PAGAMENTO ######################################
###criar pagamento
POST {{base_url}}/pagamentos/cadastrar
Content-Type: application/json

[
    {
        "formaDePagamento": "dinheiro"
    },
    
    {
        "formaDePagamento": "cartão de crédito"
    }
]

### listar pagamento
GET {{base_url}}/pagamentos/listar

### alterar pagamento
PUT {{base_url}}/pagamentos/alterar/224411f7-4f2e-4758-8b34-eb3d5e68668c
Content-Type: application/json

{
    "formaDePagamento": "cartão de débito"
}

### deletar pagamento
DELETE {{base_url}}/pagamentos/deletar/a93dadf6-adf7-4cd3-8ca5-fea07baab617

# FUNCIONARIO ######################################
###criar funcionario
POST {{base_url}}/funcionarios/cadastrar
Content-Type: application/json

[
    {
        "nome" : "Carlos Drummond de Andrade",
        "usuario" : "carlos",
        "senha": "poetamaster"
    },
    
    {
        "nome" : "Manuel Bandeira",
        "usuario" : "manuel",
        "senha": "modernismo"
    }
]

### listar funcionario
GET {{base_url}}/funcionarios/listar

### alterar funcionario
PUT {{base_url}}/funcionarios/alterar/carlos
Content-Type: application/json

{
    "nome" : "Joaquim Maria Machado de Assis",
    "usuario" : "joaquim",
    "senha": "maioral"
}

### deletar funcionario
DELETE {{base_url}}/funcionarios/deletar/manuel