@base_url= http://localhost:5223

# CLIENTE ######################################
###criar cliente
POST {{base_url}}/clientes/cadastrar
Content-Type: application/json

[
    {
        "nome": "Thiago Schwantes",
        "cpf" : "12345678910",
        "rg" : "123456789",
        "cep" : "81220450",
        "endereco" : "rua mario souza francisco 220",
        "bairro" : "boqueirão",
        "cidade" : "curitiba",
        "telefone" : "41999889988"
    },
    
    {
        "nome": "Vinicius Ferreira Geraldo",
        "cpf" : "0957261901",
        "rg" : "109103500",
        "cep" : "81333900",
        "endereco" : "rua caronel tadalafila 850",
        "bairro" : "campo cumprido",
        "cidade" : "paranagua",
        "telefone" : "41986861122"
    }
]

### buscar cliente
GET {{base_url}}/cliente/buscar/11

### listar cliente
GET {{base_url}}/clientes/listar

### alterar cliente pelo cpf
PUT {{base_url}}/clientes/alterar/7
Content-Type: application/json

{
    "nome": "Marcos Lopes",
    "cpf" : "109103500",
    "rg" : "999999999",
    "cep" : "82666300",
    "endereco" : "rua jose alfredo lopes 850",
    "bairro" : "fazendinha",
    "cidade" : "Londrina",
    "telefone" : "41984562020"
}

### deletar cliente
DELETE {{base_url}}/clientes/deletar/14

# VENDEDOR ######################################
###cadastro vendedor
POST {{base_url}}/vendedores/cadastrar
Content-Type: application/json

[
    {
        "nome" : "Carlos Drummond de Andrade",
        "usuario" : "carlos",
        "senha": "poetamaster"
    },
    
    {
        "nome" : "Manuel Bandeira",
        "usuario" : "manuel",
        "senha": "modernismo"
    }
]

### listar vendedor
GET {{base_url}}/vendedores/listar

### alterar vendedor pelo usuario
PUT {{base_url}}/vendedores/alterar/1
Content-Type: application/json

{
    "nome" : "Joaquim Maria Machado de Assis",
    "usuario" : "joaquim",
    "senha": "maioral"
}

### deletar vendedor pelo usuario
DELETE {{base_url}}/vendedores/deletar/2

# ACABAMENTO ######################################
###criar acabamento
POST {{base_url}}/acabamentos/cadastrar
Content-Type: application/json

[
    {
        "nome": "acabamento de adesivo",
        "descricao" : "refile com estilete pequeno na linha de corte e aplicação se necessario"
    },
    
    {
        "nome": "acabamento de banner",
        "descricao" : "refile com estilete grande,solda com maquina de solda,grampeia as madeiras e bambante encima e embaixo,depois coloca a ponteira e grampeia."
    }
]

### buscar acabamento
GET {{base_url}}/acabamento/buscar/1

### listar acabamento
GET {{base_url}}/acabamentos/listar

### alterar acabamento
PUT {{base_url}}/acabamentos/alterar/1
Content-Type: application/json

{
    "nome": "acabamento em lona",
    "descricao" : "solda com a maquina de solda e depois passa ela pela maquina de ilhós."
}

### deletar acabamento
DELETE {{base_url}}/acabamentos/deletar/2

# EQUIPAMENTO ######################################
###criar equipamento
POST {{base_url}}/equipamentos/cadastrar
Content-Type: application/json

[
    {
        "nome": "My Jet",
        "descricao" : "Maquina de impressão para grandes formatos,com capacidade de ate 3.20 de largura, 8 cabeças com tinta a base de solvente."
    },
    
    {
        "nome": "Rolland",
        "descricao" : "Maquina de impressão para impressão de adesivo com 4 cabeças e tinta a base de solvente."
    }
]

### listar equipamento
GET {{base_url}}/equipamentos/listar

### alterar equipamento
PUT {{base_url}}/equipamentos/alterar/1
Content-Type: application/json

{
    "nome": "Plotter",
    "descricao" : "Maquina para corte de adesivo e corte contorno após impressão."
}

### deletar equipamento
DELETE {{base_url}}/equipamentos/deletar/2

# ORDEM DE SERVIÇO ######################################
###criar OS
POST {{base_url}}/ordem-servico/cadastrar
Content-Type: application/json

[
    {
        "observacoes": "faça a impressão na melhor qualidade.",
        "clienteId": 1,
        "vendedorId": 1
    },
    
    {
        "observacoes": "cuidado extra no acabamento.",
        "clienteId": 1,
        "vendedorId": 1
    }
]

### listar OS
GET {{base_url}}/ordem-servico/listar

### buscar Os
GET {{base_url}}/ordem-servico/buscar/3

### alterar OS
PUT {{base_url}}/ordem-servico/alterar/1
Content-Type: application/json

{
    "observacoes": "observacao alterada",
    "clienteId": 1,
    "vendedorId": 1
}

### deletar OS
DELETE {{base_url}}/ordem-servico/deletar/2


# PRODUTO ######################################
###criar produto
POST {{base_url}}/produtos/cadastrar
Content-Type: application/json

[
    {
        "nome": "lona",
        "descricao" : "lona 440g branco front-light com fundo black",
        "largura": 2.5,
        "altura": 2.5,
        "valorM2": 35,
        "quantidade": 10,
        "equipamentoId": 1,
        "acabamentoId": 1,
        "ordemServicoId": 1
    }
]

### listar produto
GET {{base_url}}/produtos/listar


### buscar produto
GET {{base_url}}/produtos/buscar/4

### alterar produto
PUT {{base_url}}/produtos/alterar/3
Content-Type: application/json

{
    "nome": "adesivo transparente",
    "descricao" : "adesivo transparente 10mm brilho,marca viniLona",
    "preco" : 45.00
    
}

### deletar produto
DELETE {{base_url}}/produtos/deletar/1

# VALIDAÇÃO DE ACESSO ############################
###validando acesso
POST {{base_url}}/vendedor/validacaoAcesso
Content-Type: application/json

{
    "usuario": "joaquim",
    "senha" : "maioral"
}

# STATUS #####################
### incrementando status
PUT {{base_url}}/ordem-servico/alterarStatus/1
Content-Type: application/json

###listando OS para demonstração do incremento acima
GET {{base_url}}/ordem-servico/listar

# Solicitação de Baixa ############################
###Criar uma nova solicitação
POST {{base_url}}/solicitar-baixa/1
Content-Type: application/json

{
    "valorDesconto": 100,
    "pagamentos":[
        {
            "forma": 0,
            "valor": 2400,
            "OrdemServicoId": 1 
        },
        {
            "forma": 1,
            "valor": 1875,
            "OrdemServicoId": 1 
        }
    ]
}

###-Listar solitação de baixa junto com ordem de
###   serviço e altera o status para 3-solitadoBaixa
GET {{base_url}}/solicitar-baixa/listar

###Autorizar a baixa e altera status para 4-baixada
PATCH  {{base_url}}/solicitar-baixa/autorizar/13

###listando OS para demonstração do status acima
GET {{base_url}}/ordem-servico/listar